### ISSUE TITLE
为 Halo 2.0 提供插件开发的文档

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/docs#113]
目前 Halo 2.0 已经支持了插件机制，期望为插件开发编写文档。

/kind documentation

**Comment by guqing** [comment]
大纲：
- [ ] 介绍 - 对插件进行整体描述包括功能、插件API访问、核心接口、用户操作、插件管理等的概述
- [ ] 先决条件 - 插件所需运行环境和准备
- [ ] 插件结构和生命周期
- [ ] 编写自己的插件 - 一步步介绍如何创建一个自己的插件
  - [ ] 使用模板创建一个新的插件项目
  - [ ] 初始化插件
  - [ ] 创建一个自定义模型
  - [ ] 使用 Halo 资源
  - [ ] 使用外部资源
  - [ ] 创建用户界面
  - [ ] 如何测试插件代码
  - [ ] 调试
  - [ ] 构建 JAR
- [ ] Halo 扩展点

**Comment by ruibaby** [comment]
@guqing 我建议先有一个简单的从创建项目到运行起来看到效果的文档。然后再持续深入。

**Comment by guqing** [comment]
> 

没有深入的点，介绍只是整体概述，然后就是创建插件了
