### ISSUE TITLE
添加更新 Halo 2.x 的文档

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/docs#150]
目前，我们仅提供了用 Docker 或 Docker Compose 安装 Halo 2.0 的文档，但是还缺少如何更新 Halo 2.x 的文档。

参考：
- <https://bbs.halo.run/d/3095-20%E5%8D%87%E7%BA%A7%E9%95%9C%E5%83%8F%E5%92%8C1x%E7%9A%84%E4%B8%80%E6%A0%B7%E5%90%97>

**Comment by ruibaby** [comment]
Docker Compose 是有更新版本的文档的：https://docs.halo.run/getting-started/install/docker-compose/#%E6%9B%B4%E6%96%B0%E5%AE%B9%E5%99%A8%E7%BB%84

需要补充单纯使用 Docker 的更新文档。
