### ISSUE TITLE
cpu占用率100%

### ISSUE THREAD

**Issue by dqswan18** [halo-dev/docs#204]
每次重新拉取Docker并启动，CPU占用率瞬间会拉到120%以上，大概持续3分钟才可以，不知道是不是我系统问题。
目前我的系统为Ubuntu 22.04  服务器上运行的服务有宝塔和宝塔的JAVA管理器的一个图床项目，剩下的就只有Halo了。但是我不确定是我自身问题，还是Halo问题。谢谢！

**Comment by JohnNiang** [comment]
目前 Halo 的设计就是如此。Halo 在启动的时候会获取所有的数据并进行检查，例如：发布文章，注册路由，构建搜索索引等。

**Comment by JohnNiang** [comment]
这个问题我们会持续优化，建议保持 Halo 至最新版。我将关闭当前 Issue，有任何问题可随时重新打开。

/kind improvement
/close
