### ISSUE TITLE
developer-guide/form-schema 中Schema链接 404

### ISSUE THREAD

**Issue by AirboZH** [halo-dev/docs#223]
https://github.com/halo-dev/docs/blob/4b934c0ace0fcff13bd6a2cb06b8171e10eebfad/docs/developer-guide/form-schema.md?plain=1#L11-L13 

上面两个链接是无法访问的，或许地址已经迁移。想表达的可能是?
```
https://formkit.com/essentials/schema
```

**Comment by ruibaby** [comment]
应该是他们文档地址改了。

PR Welcome :)
