### ISSUE TITLE
Bug: Thymeleaf元素实际赋值与文档不一致

### ISSUE THREAD

**Issue by allinprogram** [halo-dev/docs#259]
https://docs.halo.run/developer-guide/theme/annotations

文档中介绍的获取菜单名称的方式`${menuItem.spec.displayName}`在v2.9中是不正确的，实际在使用的是`${menuItem.status.displayName}`。

本想直接提交PR，但是捉摸不透到底是代码需要改还是文档需要改。

请查收。

**Comment by ruibaby** [comment]
这个问题在 https://github.com/halo-dev/docs/pull/252 修复过，但好像没有修改 2.9 版本的文档，如果你有兴趣可以帮忙修改一下。

**Comment by allinprogram** [comment]
感谢回复，已经提交PR：

https://github.com/halo-dev/docs/pull/260#event-10457119790
