### ISSUE TITLE
Task 'bootRun' not found in root project 'plugin-starter'.

### ISSUE THREAD

**Issue by 187264733** [halo-dev/docs#264]
安装https://docs.halo.run/category/%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91 
一步一步操作
最后运行：
 # Windows
gradlew.bat bootRun --args="--spring.profiles.active=dev,win,local"
报错

**Comment by JohnNiang** [comment]
需要看看具体报什么错。

/triage needs-information

**Comment by 187264733** [comment]
搞定了， 你那边有插件开发的比较详细的文档？我准备开发几个插件放商店里

**Comment by JohnNiang** [comment]
这里推荐几个视频：

- 【Halo 社区例会 Vol.06 从零开始的 Halo 插件开发（一）】https://www.bilibili.com/video/BV1Ek4y1u7aJ?vd_source=48e9be93ee10edc937b231ebd5328a3c
- 【Halo 社区例会 Vol.07 从零开始的 Halo 插件开发（二）】https://www.bilibili.com/video/BV1V14y1U7HB?vd_source=48e9be93ee10edc937b231ebd5328a3c
- 【Halo 社区例会 Vol.08 从零开始的 Halo 插件开发（三）】https://www.bilibili.com/video/BV1Kk4y1u7at?vd_source=48e9be93ee10edc937b231ebd5328a3c
- 【Halo 社区例会 Vol.09 插件开发工具链演示及 Halo 2.7.0 新特性介绍】https://www.bilibili.com/video/BV1Ps4y1k7Uc?vd_source=48e9be93ee10edc937b231ebd5328a3c

同时官方文档也有一个例子可供参考：

- https://docs.halo.run/developer-guide/plugin/examples/todolist

**Comment by 187264733** [comment]
谢谢，我先看看

**Comment by guqing** [comment]
参考 https://github.com/halo-dev/docs/issues/264#issuecomment-1760674416 给出的这个视频链接直接使用插件工具链来开发插件, plugin-starter 已经自带了

【Halo 社区例会 Vol.09 插件开发工具链演示及 Halo 2.7.0 新特性介绍】[bilibili.com/video/BV1Ps4y1k7Uc?vd_source=48e9be93ee10edc937b231ebd5328a3c](https://www.bilibili.com/video/BV1Ps4y1k7Uc?vd_source=48e9be93ee10edc937b231ebd5328a3c)

使用方式是先启动 docker ,然后点击 haloServer 会启动 halo 并自动将当前开发的插件安装好，然后开发插件对于后端代码改完以后需要点击 reloadPlugin 来重载插件以使插件改动代码生效，对于改动前端部分只需要在开发时运行 pnpm dev 即可会实时生效

<img width="469" alt="image" src="https://github.com/halo-dev/docs/assets/38999863/18c582d7-32a7-48e4-ad58-defed0c44b4c">

**Comment by guqing** [comment]
并不清楚你说的本地安装插件会自己消失是怎么操作的，可以提供复现步骤，目前没有发现有这个问题,
另外如果你没有 docker 要开发插件，可以在详细参考文档运行 halo 来使用
https://docs.halo.run/developer-guide/core/run

文档中的运行 Console 和运行 Halo 两个步骤都是必要的, 都需要按文档操作
