### ISSUE TITLE
开发文档的代码风格部分需要标注 checkstyle 的版本。

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/docs#29]
https://bbs.halo.run/d/2062-idea2021-checkstyle-scope

https://github.com/halo-dev/halo/issues/1470#issuecomment-915911208

**Comment by ruibaby** [comment]
@JohnNiang 有时间加一下吗

**Comment by JohnNiang** [comment]
@ruibaby ,好的，我稍后优化一下文档。
