### ISSUE TITLE
代码框格式错乱

### ISSUE THREAD

**Issue by NikoYomi** [halo-dev/docs#297]
问题一：代码块内容格式错乱。
问题二：代码块胖的复制点击失效。
如图：
编辑界面：
![1703037706982](https://github.com/halo-dev/docs/assets/120245220/4e300019-8334-4ad9-b19b-e8d7f07b05af)
预览界面：
![1703037661367](https://github.com/halo-dev/docs/assets/120245220/205acdf5-e86d-44c8-9cf2-79c1c9519e02)

**Comment by JohnNiang** [comment]
Hi @NikoYomi , thank you for reaching out here!

请到对应的主题仓库提交 Issue，当前仓库主要维护官方文档。

/triage unresolved
/close
