### ISSUE TITLE
自定义元数据时，文档编写不清晰

### ISSUE THREAD

**Issue by xiaoming728** [halo-dev/docs#298]
<img width="660" alt="image" src="https://github.com/halo-dev/docs/assets/62709839/68a5ff64-0eac-4f29-8f7e-fe87542c5c35">
generateName每次启用插件都会创建一次，导致开发和使用时出现多条相同或历史的元数据，文档中没有说明

**Comment by JohnNiang** [comment]
Hi @xiaoming728 ，thank you for reaching out here!

确认这是一个问题。

/kind bug
/ping @halo-dev/sig-docs
