### ISSUE TITLE
文档指定的checkstyle版本过时

### ISSUE THREAD

**Issue by mashirot** [halo-dev/docs#329]
[文档中](https://docs.halo.run/developer-guide/core/code-style)指定版本为8.39
在IDEA 23.3.5 CheckStyle 5.88.1下，如下图所示，已无此版本
![image](https://github.com/halo-dev/docs/assets/52254895/aea9ce17-267e-47a6-8637-0a5b290ca4b2)

**Comment by JohnNiang** [comment]
Hi @mashirot , thank you for reaching out here!

Good catch!

从 https://github.com/halo-dev/halo/blob/fa26516ecc9fa93ea2e43f02b018b1c843f27653/application/build.gradle#L26 可以看到，Checkstyle 版本应该设置为 9.3，而不是 8.39。

如果有兴趣话，欢迎提交 PR 修改文档。

**Comment by mashirot** [comment]
> Hi @mashirot , thank you for reaching out here!
> 
> Good catch!
> 
> 从 https://github.com/halo-dev/halo/blob/fa26516ecc9fa93ea2e43f02b018b1c843f27653/application/build.gradle#L26 可以看到，Checkstyle 版本应该设置为 9.3，而不是 8.39。
> 
> 如果有兴趣话，欢迎提交 PR 修改文档。

see #330
