### ISSUE TITLE
请问怎么在插件声明免签权的接口供外部服务访问，比如微信

### ISSUE THREAD

**Issue by ariwori** [halo-dev/docs#349]
请问怎么在插件声明免签权的接口供外部服务访问，比如微信

**Comment by ruibaby** [comment]
可以参考：https://docs.halo.run/developer-guide/plugin/api-reference/server/role-template#%E8%81%9A%E5%90%88%E8%A7%92%E8%89%B2:~:text=%E8%B5%84%E6%BA%90%E5%9E%8B%20APIs-,%E5%85%AC%E5%BC%80%E7%BB%99%E6%89%80%E6%9C%89%E7%94%A8%E6%88%B7%E8%AE%BF%E9%97%AE,-%EF%BC%8C%E8%BF%99%E6%97%B6%E4%BD%A0%E5%8F%AF%E4%BB%A5

**Comment by guqing** [comment]
see also https://github.com/halo-dev/plugin-starter/issues/33

/close
