### ISSUE TITLE
主题模版变量获取树结构的文章分类列表

### ISSUE THREAD

**Issue by mqllin** [halo-dev/docs#36]
### 描述一下此特性

参考获取多级菜单的标签，使用<@categoryTag method="tree"> 标签可以成功获取到树结构的文章分类列表但文档中没有提及。建议补充[文档说明](https://docs.halo.run/developer-guide/theme/template-tag#%E8%8E%B7%E5%8F%96%E6%89%80%E6%9C%89%E5%88%86%E7%B1%BB%E7%9B%AE%E5%BD%95list)。

**Comment by JohnNiang** [comment]
@mqllin 

欢迎提交 PR 来一起完善文档。

请参考：https://github.com/halo-dev/docs/blob/main/docs/developer-guide/theme/template-tag.md

**Comment by mqllin** [comment]
> 

我不会JAVA并且我仅仅是得到了树结构的dom节点，其中返回的属性字段我无法得知。所以无法提交完整的相关文档。还是希望大佬抽空看一看🙏

**Comment by ruibaby** [comment]
@mqllin 已添加。https://docs.halo.run/developer-guide/theme/template-tag#%E8%8E%B7%E5%8F%96%E5%88%86%E7%B1%BB%E7%9B%AE%E5%BD%95%E6%A0%91%E7%BB%93%E6%9E%84tree
