### ISSUE TITLE
Request to configure `file.encoding` property for running with Jar file

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/docs#457]
Recently, I found that some users encountered a problem of invalid characters when running Halo with Jar file and using Java 17 in some specific platforms.

But when we configure `file.encoding` to `UTF-8`,  the problem disappears. Please note that, it is not necessary to specify `file.encoding` to `UTF-8` while using versions after Java 17, as it is the default. See [JEP 400](https://openjdk.org/jeps/400) for more.

#### References
- https://github.com/halo-dev/halo/issues/6973#issuecomment-2448904235
- https://github.com/halo-dev/halo/issues/6937
- https://openjdk.org/jeps/400

**Comment by ruibaby** [comment]
Since Java 17 and above has been specified as UTF-8 by default, why is this problem still there?
