### ISSUE TITLE
添加 1.5.0 Redis 缓存配置的文档。

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/docs#52]
RT

**Comment by ruibaby** [comment]
在这个位置：https://github.com/halo-dev/docs/blob/main/docs/getting-started/config.md#%E7%BC%93%E5%AD%98

**Comment by luoxmc** [comment]
> /cc @luoxmc 你好，可以帮我们补充一下这块儿文档吗？

你好，已发pr
