### ISSUE TITLE
使用tencentCloudBase无法部署

### ISSUE THREAD

**Issue by BoWang816** [halo-dev/docs#73]
在使用tencentCloudBase部署时，因为项目模板是在github上面，代码会拉不下来，请求一直超时导致部署失败；

所以只好将GitHub的代码clone下来，放到gitee，修改为gitee的地址后正常才可以正常部署。

希望官方文档能够更新一下

**Comment by ruibaby** [comment]
see https://gitee.com/halo-dev/tencent-cloudbase-halo

可以添加一个额外的按钮。

/kind documentation
/good-first-issue

**Comment by Aanko** [comment]
/ assign
