### ISSUE TITLE
图库根据分组获取图片（listByTeam）示例错误

### ISSUE THREAD

**Issue by vayci** [halo-dev/docs#85]
## 错误位置

[图库#根据分组获取图片（listbyteam）](https://docs.halo.run/developer-guide/theme/template-tag#%E6%A0%B9%E6%8D%AE%E5%88%86%E7%BB%84%E8%8E%B7%E5%8F%96%E5%9B%BE%E7%89%87listbyteam)

## 错误描述
method listByTeam 示例为 listTeams，并且示例中遍历时使用team对象进行遍历

**Comment by ruibaby** [comment]
PR welcome :)

看到你之前提过一个 [PR](https://github.com/halo-dev/docs/pull/84)，是遇到了什么问题然后关闭了吗？

**Comment by vayci** [comment]
> PR welcome :)
> 
> 看到你之前提过一个 [PR](https://github.com/halo-dev/docs/pull/84)，是遇到了什么问题然后关闭了吗？

我以为没有提issue，PR流程上不规范，就先关闭了。

**Comment by ruibaby** [comment]
> > PR welcome :)
> > 看到你之前提过一个 [PR](https://github.com/halo-dev/docs/pull/84)，是遇到了什么问题然后关闭了吗？
> 
> 我以为没有提issue，PR流程上不规范，就先关闭了。

Fix 类型可以直接提交 PR。 我先帮你 reopen。
